# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

env:
  GOOS: linux
  GOARCH: amd64

permissions:
  packages: write

jobs:

  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch:
          - amd64
          - arm64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'

    - name: Build
      run: go build -v -o k8s-test-job .
      env:
        GOARCH: ${{ matrix.arch }}

    - name: Store artifact
      uses: actions/upload-artifact@v4
      with:
        name: k8s-test-job-artifact
        path: k8s-test-job
        if-no-files-found: error

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
   
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/kbugaienko/k8s-test-task:latest
        platforms: linux/${{ matrix.arch }}
